project_id = "qpjdiargpivwtbakkfpo"

[functions.ai-assist]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-admission-email]
verify_jwt = false

[functions.mapbox-directions]
verify_jwt = false
