// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpjdiargpivwtbakkfpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwamRpYXJncGl2d3RiYWtrZnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDE3NDEsImV4cCI6MjA2NDQ3Nzc0MX0.vbkDilhx8rdeaf0ZihRontOi0Z2ehWyI_62uc6pjbmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);