// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-referrals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.23.8";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_referrals_default = defineTool({
  name: "list_referrals",
  title: "List referrals",
  description: "List hospice referrals visible to the signed-in user, most recent first. Optionally filter by status, priority, or assigned marketer.",
  inputSchema: {
    status: z.string().optional().describe("Referral status (e.g. new_referral, contacted, assessment_scheduled, admitted, discharged)."),
    priority: z.enum(["routine", "urgent", "stat"]).optional(),
    assigned_marketer: z.string().optional().describe("Email or name of the assigned marketer."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, priority, assigned_marketer, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = clientFor(ctx).from("referrals").select(
      "id, patient_name, status, priority, diagnosis, referral_source, organization_id, assigned_marketer, created_at, contact_date"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (priority) q = q.eq("priority", priority);
    if (assigned_marketer) q = q.eq("assigned_marketer", assigned_marketer);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { referrals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-referral.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.23.8";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_referral_default = defineTool2({
  name: "get_referral",
  title: "Get referral",
  description: "Fetch a single referral by its UUID, including clinical and source details.",
  inputSchema: { id: z2.string().uuid().describe("Referral UUID.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await clientFor2(ctx).from("referrals").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Referral not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { referral: data }
    };
  }
});

// src/lib/mcp/tools/list-organizations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.23.8";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_organizations_default = defineTool3({
  name: "list_organizations",
  title: "List partner organizations",
  description: "List referring/partner organizations (facilities, physician groups, SNFs). Optional text search on name and city.",
  inputSchema: {
    search: z3.string().optional().describe("Case-insensitive substring match against name or city."),
    account_rating: z3.enum(["A", "B", "C", "D"]).optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, account_rating, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = clientFor3(ctx).from("organizations").select(
      "id, name, organization_type, account_rating, partnership_stage, city, state, last_contact_date, next_followup_date, is_active"
    ).eq("is_active", true).order("last_contact_date", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (account_rating) q = q.eq("account_rating", account_rating);
    if (search) q = q.or(`name.ilike.%${search}%,city.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { organizations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/upcoming-visits.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.23.8";
function clientFor4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var upcoming_visits_default = defineTool4({
  name: "upcoming_visits",
  title: "Upcoming visits",
  description: "List scheduled visits in the next N days (default 7), soonest first.",
  inputSchema: {
    days: z4.number().int().min(1).max(60).optional(),
    assigned_to: z4.string().optional().describe("Filter by assigned staff email or name."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ days, assigned_to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const now = /* @__PURE__ */ new Date();
    const end = new Date(now.getTime() + (days ?? 7) * 864e5);
    let q = clientFor4(ctx).from("visits").select("*").gte("visit_date", now.toISOString()).lte("visit_date", end.toISOString()).order("visit_date", { ascending: true }).limit(limit ?? 50);
    if (assigned_to) q = q.eq("assigned_to", assigned_to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { visits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/dashboard-stats.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.50.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
function clientFor5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var dashboard_stats_default = defineTool5({
  name: "dashboard_stats",
  title: "Dashboard stats",
  description: "Aggregate CRM KPIs: current census, monthly referral counts, conversion rate, and average response time.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await clientFor5(ctx).rpc("get_dashboard_stats");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { stats: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qpjdiargpivwtbakkfpo";
var mcp_default = defineMcp({
  name: "elevate-hospice-mcp",
  title: "Elevate Hospice Referral Dashboard",
  version: "0.1.0",
  instructions: "Read tools over the Elevate Hospice referral CRM. Each caller acts as their own signed-in user; Row Level Security applies. Use `list_referrals` and `get_referral` to look up hospice referrals, `list_organizations` for partner facilities, `upcoming_visits` for the schedule, and `dashboard_stats` for KPIs.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_referrals_default, get_referral_default, list_organizations_default, upcoming_visits_default, dashboard_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
