-- Insert Tier 1: Immediate Outreach Targets
INSERT INTO public.organizations (
  name, type, address, phone, contact_person, contact_email, bed_count, 
  partnership_stage, partnership_priority_level, relationship_status, 
  partnership_notes, estimated_monthly_referrals, assigned_marketer
) VALUES 
(
  'Life Care Center of Paradise Valley',
  'nursing_home',
  '4065 E. Bell Road, Phoenix, AZ 85032',
  '(602) 867-0212',
  NULL,
  NULL,
  210,
  'prospect',
  'high',
  'prospect',
  'Tier 1 Target: High volume opportunity despite quality issues; corporate may seek alternative hospice partners. Recent infection control violations noted. Ownership: Life Care Centers of America (200+ facilities nationally)',
  25,
  NULL
),
(
  'Palm Valley Rehabilitation and Care Center',
  'nursing_home',
  '13575 West McDowell Road, Goodyear, AZ 85338',
  NULL,
  NULL,
  NULL,
  170,
  'prospect',
  'high',
  'prospect',
  'Tier 1 Target: Large West Valley facility in underserved growth area; no identified exclusive hospice relationships. For-profit independent ownership.',
  20,
  NULL
),
(
  'Horizon Post Acute and Rehabilitation Center',
  'nursing_home',
  'Glendale, AZ 85302',
  NULL,
  NULL,
  NULL,
  196,
  'prospect',
  'high',
  'prospect',
  'Tier 1 Target: Highest bed count in West Valley; densely populated area with 38,000+ surrounding residents. For-profit ownership.',
  22,
  NULL
),
(
  'Bella Vita Health and Rehabilitation Center',
  'nursing_home',
  'Maryvale area, Glendale',
  NULL,
  NULL,
  NULL,
  186,
  'prospect',
  'high',
  'prospect',
  'Tier 1 Target: Large facility in high-density area (61,000 residents); Maryvale demographics align with underserved populations. For-profit ownership.',
  21,
  NULL
),
(
  'Phoenix Mountain Post-Acute (Ensign Group)',
  'nursing_home',
  '13232 N. Tatum Blvd, Phoenix, AZ 85032',
  '(602) 996-5200',
  NULL,
  'contact-PhoenixMountain@ensignservices.net',
  130,
  'prospect',
  'high',
  'prospect',
  'Tier 1 Target: Part of major chain with standardized partnership processes; North Phoenix location complements West Valley focus. Ownership: The Ensign Group Inc.',
  15,
  NULL
),

-- Insert Tier 2: High-Quality Partnership Opportunities
(
  'Camelback Post-Acute Care and Rehabilitation',
  'nursing_home',
  '4635 N. 14th St, Phoenix, AZ 85014',
  '(602) 264-9039',
  'Aaron Fuller',
  'afuller@camelbackrehab.com',
  107,
  'prospect',
  'high',
  'prospect',
  'Tier 2 Target: Premium quality facility with established administrator contact; central Phoenix location. 5-star CMS rating (top 10% nationally).',
  12,
  NULL
),
(
  'Haven Health Phoenix',
  'nursing_home',
  '4202 North 20th Ave, Phoenix, AZ 85015',
  '(602) 264-3824',
  'Casey Ivancich',
  'civancich@havenhealthaz.com',
  100,
  'prospect',
  'high',
  'prospect',
  'Tier 2 Target: Regional chain with multiple facilities; established contact information. Ownership: Haven Health Group LLC.',
  12,
  NULL
),
(
  'Haven Health Sky Harbor',
  'nursing_home',
  '1880 E. Van Buren St, Phoenix, AZ 85006',
  '(602) 253-4570',
  'Mitchell Brady',
  'mbrady@havenhealthaz.com',
  120,
  'prospect',
  'high',
  'prospect',
  'Tier 2 Target: Specialized services align with complex hospice cases; private rooms enhance family experience. Specialties: Advanced respiratory care, tracheostomy, ventilation.',
  14,
  NULL
),
(
  'Sun City Health and Rehabilitation Center',
  'nursing_home',
  '9940 West Union Hills Drive, Sun City, AZ 85373',
  NULL,
  NULL,
  NULL,
  118,
  'prospect',
  'high',
  'prospect',
  'Tier 2 Target: Sun City demographics ideal for hospice services; established facility since 1994. Medicare License: #35225.',
  14,
  NULL
),
(
  'Banner Boswell Rehabilitation Center',
  'nursing_home',
  '10601 West Santa Fe Drive, Sun City, AZ 85351',
  '(623) 832-7000',
  NULL,
  NULL,
  115,
  'prospect',
  'high',
  'prospect',
  'Tier 2 Target: Despite Banner Hospice affiliation, nonprofit status may allow concurrent partnerships. Ownership: Banner Health (nonprofit). CMS Rating: 4-5 stars.',
  13,
  NULL
),

-- Insert Tier 3: Strategic Geographic Expansion
(
  'Desert Terrace Healthcare Center (Ensign Group)',
  'nursing_home',
  '2509 North 24th Street, Phoenix, AZ 85008',
  '(602) 273-1347',
  NULL,
  'contact-desertterrace@ensignservices.net',
  100,
  'prospect',
  'medium',
  'prospect',
  'Tier 3 Target: Central Phoenix location; Ensign Group standardization benefits.',
  11,
  NULL
),
(
  'La Estancia Nursing and Rehabilitation (Genesis Healthcare)',
  'nursing_home',
  '15810 South 42nd Street, Phoenix, AZ 85048',
  '(480) 759-0358',
  'Dr. Ronald Kane',
  NULL,
  NULL,
  'prospect',
  'medium',
  'prospect',
  'Tier 3 Target: South Phoenix coverage; Genesis corporate relationships scalable. Ownership: Genesis Healthcare (290+ facilities nationally). Medical Director: Dr. Ronald Kane.',
  10,
  NULL
),
(
  'Desert Haven Nursing Center',
  'nursing_home',
  '2645 E. Thomas Rd, Phoenix, AZ 85016',
  '(602) 956-8000',
  'Jayson Hunt',
  'jhunt@dhccaz.com',
  115,
  'prospect',
  'medium',
  'prospect',
  'Tier 3 Target: Central/East Phoenix location with established administrator contact.',
  13,
  NULL
),
(
  'Advanced Health Care of Glendale',
  'nursing_home',
  '16825 N. 63rd Ave, Glendale, AZ 85306',
  '(602) 732-3400',
  'Wyatt Caldwell',
  'WCaldwell@ahcfacilities.com',
  54,
  'prospect',
  'medium',
  'prospect',
  'Tier 3 Target: Smaller high-quality facility; Advanced Health Care chain presence. U.S. News "High Performing" rating.',
  6,
  NULL
),
(
  'Christian Care Nursing Center',
  'nursing_home',
  '11812 North 19th Ave, Phoenix, AZ 85029',
  '(602) 443-5405',
  NULL,
  NULL,
  68,
  'prospect',
  'medium',
  'prospect',
  'Tier 3 Target: Faith-based nonprofit with exceptional quality ratings; smaller size allows personalized partnership. 5-star U.S. News rating. Ownership: Nonprofit, Fellowship Square.',
  7,
  NULL
);