-- Ensure RLS is enabled on all PHI tables (no-op if already enabled)
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospice_referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bereavement_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.care_team_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- DROP all dangerous dreamlit policies that allow public unauthenticated access
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.patients;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.referrals;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.hospice_referrals;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.patient_documents;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.patient_attachments;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.patient_evaluations;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.bereavement_tracking;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.care_team_assignments;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.organizations;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.organization_contacts;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.organization_documents;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.organization_checklists;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.organization_kpis;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.organization_training_modules;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.activity_communications;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.activity_log;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.communication_templates;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.admission_data;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.census_entries;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.checklist_completions;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.competitive_analysis;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.compliance_metrics;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.hospice_profiles;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.liaison_goals;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.marketer_training_progress;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.partnership_agreements;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.partnership_performance_metrics;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public."Elevate CRM";
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.profiles;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.psr_data;
DROP POLICY IF EXISTS "dreamlit_dreamlit_app_select_policy" ON public.user_roles;